# Generated by Django 4.1.5 on 2023-03-21 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_middleware", "0001_squashed_0023_alter_middleware_my_logger_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="middleware_my_logger",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
