# Generated by Django 4.1.5 on 2023-02-21 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_contact_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, max_length=255, null=True, upload_to="contacts/contact/avatar/"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.operator",
            ),
        ),
    ]
