# Generated by Django 4.1.5 on 2023-02-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0006_alter_contact_avatar_alter_contact_operator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, max_length=300, null=True, upload_to="contacts/contact/avatar/"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="contacts.operator",
            ),
        ),
    ]
