# Generated by Django 4.1.5 on 2023-02-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_squashed_0002_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, max_length=300, null=True, upload_to="contacts/contact/avatar/"
            ),
        ),
    ]
