# Generated by Django 4.1.5 on 2023-03-25 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryLogger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=250)),
                ("user_is_authenticated", models.BooleanField(default=False)),
                ("session_id", models.CharField(blank=True, default=None, max_length=100, null=True)),
                ("visit_time", models.DateTimeField(auto_now=True)),
                ("count_requests", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
