# Generated by Django 4.1.5 on 2023-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("middleware_loggers", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="querylogger",
            constraint=models.UniqueConstraint(
                fields=("path", "user", "session_id", "user_is_authenticated"), name="unique_row"
            ),
        ),
    ]
